version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      linting-toolchain:
        patterns:
          - typescript
          - typescript-eslint
          - eslint
          - eslint-*
          - '@eslint/*'
          - '@next/eslint-plugin-next'
      js-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - typescript
          - typescript-eslint
          - eslint
          - eslint-*
          - '@eslint/*'
          - '@next/eslint-plugin-next'
